version: '3.8'

services:
  nginx-azure-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-azure-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - proxy-network
    environment:
      - TZ=UTC
    volumes:
      # Mount logs to host for persistence and monitoring
      - ./logs:/var/log/nginx:rw
      # Optional: Mount custom nginx config if you want to modify without rebuilding
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "com.docker.compose.project=nginx-azure-proxy"
      - "description=NGINX reverse proxy for Azure Blob Storage URL masking"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits to prevent container from using too many resources
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    # Security options
    security_opt:
      - no-new-privileges:true
    # Read-only root filesystem for security (logs are on volume)
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /var/cache/nginx:noexec,nosuid,size=50m
      - /var/run:noexec,nosuid,size=10m

networks:
  proxy-network:
    driver: bridge
    name: nginx-azure-proxy-network

# Optional: Add a volume for persistent logs
volumes:
  nginx-logs:
    driver: local